/**
 * User: Ian Crowe
 * Date: 24/10/12
 * Time: 10:46
 */
/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Solution2 {
    public static void main(String args[]){
        int b=1;
        int c=1;
        int sum=0;

        for(int a=1;  a < 4000000;){
            a=b+c;
            c=b;
            b=a;

            if(a%2==0) sum+=a;
        }
        System.out.println(sum);
    }
}
